### ISSUE TITLE
issues with creating campa.ini with campa setup commandline

### ISSUE THREAD

**Issue by kangsan422** [theislab/campa#12]
Dear Developers,

I am using a lab cluster (cpu) to test CAMPA out. 

![image](https://user-images.githubusercontent.com/72509917/178344443-5ce7e2d0-bce9-42ec-ba62-fa724952228a.png)

It appears that /home/bkang/.config/ directory does not exist. Please help!

**Comment by hspitzer** [comment]
@kangsan422 thanks for checking CAMPA out and reporting this error. There was a bug in the code which prevented the campa config file from being created when `~/.config` does not exist. I have pushed a fix to `develop`, and will include this in a new release in the next days.

If you install CAMPA from the develop branch (`pip install git+https://github.com/theislab/campa.git@develop`), you should be able to check this code out. 
FYI, if you are calling `campa setup` from inside a Jupyer notebook, I'd recommend to include `--quiet` flag (`! campa setup --quiet`), because otherwise the script will ask you for Keyboard Input which I believe does not work within Jupyter.
You can also setup paths directly from within python:  https://campa.readthedocs.io/en/latest/notebooks/setup.html
